import { StudioService, VirtualTicket } from '../types/ticket';

export const FOTOLOU_SERVICES: StudioService[] = [
  {
    id: 'photo_identite',
    name: 'Photo d’identité Biométrique',
    category: 'Express (5 min)',
    durationMinutes: 5,
    price: 3500, // FCFA / standard
    prefix: 'ID',
    description: 'Normes passeport, visa, CNI, permis de conduire, livraison papier & email instantanée.',
  },
  {
    id: 'tirage_express',
    name: 'Tirage & Impression Express',
    category: 'Laboratoire',
    durationMinutes: 10,
    price: 5000,
    prefix: 'T',
    description: 'Développement et tirage haute définition depuis votre smartphone (WhatsApp / Bluetooth).',
  },
  {
    id: 'shooting_express',
    name: 'Shooting Portrait Studio',
    category: 'Séance Studio',
    durationMinutes: 20,
    price: 15000,
    prefix: 'S',
    description: 'Séance portrait pro / CV / réseaux avec éclairage professionnel et retouche flash.',
  },
  {
    id: 'retouche_numerique',
    name: 'Restauration & Retouche Photo',
    category: 'Créatif',
    durationMinutes: 15,
    price: 8000,
    prefix: 'R',
    description: 'Correction colorimétrique, suppression d’éléments et agrandissement grand format.',
  },
  {
    id: 'retrait_commande',
    name: 'Retrait Commande / Album',
    category: 'Retrait',
    durationMinutes: 3,
    price: 0,
    prefix: 'C',
    description: 'Récupération rapide de vos tirages, cadres et albums photo finalisés.',
  },
];

export const INITIAL_TICKETS: VirtualTicket[] = [
  {
    id: 't_001',
    ticketNumber: 'ID-042',
    serviceId: 'photo_identite',
    serviceName: 'Photo d’identité Biométrique',
    clientName: 'Mamadou Diallo',
    clientPhone: '+221 77 456 12 34',
    status: 'in_progress',
    queuePosition: 0,
    estimatedWaitMinutes: 0,
    counterNumber: 1,
    createdAt: '10:15',
    calledAt: '10:20',
  },
  {
    id: 't_002',
    ticketNumber: 'T-015',
    serviceId: 'tirage_express',
    serviceName: 'Tirage & Impression Express',
    clientName: 'Aïssatou Ndiaye',
    clientPhone: '+221 70 123 45 67',
    status: 'waiting',
    queuePosition: 1,
    estimatedWaitMinutes: 5,
    createdAt: '10:18',
  },
  {
    id: 't_003',
    ticketNumber: 'S-008',
    serviceId: 'shooting_express',
    serviceName: 'Shooting Portrait Studio',
    clientName: 'Ousmane Sow',
    clientPhone: '+221 76 987 65 43',
    status: 'waiting',
    queuePosition: 2,
    estimatedWaitMinutes: 12,
    createdAt: '10:22',
  },
];
